CREATE DATABASE PROPOSTADB;
GO

USE PROPOSTADB;
GO

CREATE TABLE PROPOSTA (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NUMERO_PROPOSTA VARCHAR(30),
    STATUS VARCHAR(15) NOT NULL, -- EM_ANALISE, APROVADA, REJEITADA
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATAHORA_INCLUSAO DATETIME2 NOT NULL,
    VALOR_PREMIO DECIMAL(10,2) NOT NULL,
    VALOR_COBERTURA DECIMAL(12,2) NOT NULL,
	
	CONSTRAINT UQ_NUMERO_PROPOSTA
        UNIQUE (NUMERO_PROPOSTA)
);
GO

CREATE DATABASE CONTRATACAODB;
GO

USE CONTRATACAODB;
GO

CREATE TABLE CONTRATACAO (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_PROPOSTA INT NOT NULL,
	NUMERO_APOLICE VARCHAR(30),
	DATAHORA_CONTRATACAO DATETIME2,
    VALOR_PREMIO_FINAL DECIMAL(10,2) NOT NULL,
    VALOR_COBERTURA_FINAL DECIMAL(12,2) NOT NULL
	
	CONSTRAINT UQ_NUMERO_APOLICE
        UNIQUE (NUMERO_APOLICE)
);
GO

--ADD EMAIL_CONTRATANTE PARA ENVIO DE NOTIFICACAO POR EMAIL
USE PROPOSTADB;
GO

ALTER TABLE PROPOSTA ADD EMAIL_CONTRATANTE VARCHAR(150);
GO

USE CONTRATACAODB;
GO

ALTER TABLE CONTRATACAO ADD EMAIL_CONTRATANTE VARCHAR(150);